name: master branch updated

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python {{ cookiecutter.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: {{ cookiecutter.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install {% if cookiecutter.dependency_management_tool == 'pipenv' -%}pipenv{%- elif cookiecutter.dependency_management_tool == 'poetry' -%}poetry{% endif -%} invoke
          inv env.init-dev --no-pre-commit

      # do not failed when there is not versioning needed (e.g., document change)
      - name: Create bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          inv git.bump

      - name: Push changes
        uses: Woile/github-push-action@master
        with:
          github_token: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
          tags: "true"

  publish-github-page:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: {% raw %}'${{ secrets.PERSONAL_ACCESS_TOKEN }}'{% endraw %}
          fetch-depth: 0

      - name: Set up Python {{ cookiecutter.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: {{ cookiecutter.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install {% if cookiecutter.dependency_management_tool == 'pipenv' -%}pipenv{%- elif cookiecutter.dependency_management_tool == 'poetry' -%}poetry{% endif -%} invoke
          inv env.init-dev --no-pre-commit

      - name: Build docs
        run: |
          inv doc.build

      - name: Push doc to Github Page
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: {% raw %}${{ secrets.PERSONAL_ACCESS_TOKEN }}{% endraw %}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site
